version: '3'
services:
  image-collector-php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html

  image-collector-nginx:
    image: nginx:1.19.2-alpine
    ports:
      - "8888:8888"
    depends_on:
      - image-collector-php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  image-collector-redis:
    image: redis:6.0.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
