monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/log.err"
            level: debug
            channels: ["!event"]
        console:
            type: stream
            path: "%kernel.logs_dir%/log.err"
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
